---
# Comprobar servicio nginx
- name: Ejecutar curl al servicio web
  shell:
    cmd: curl localhost:81
  ignore_errors: True
  register: capturado_curl

- name: Comprobar que el servicio nginx está corriendo
  assert:
    that:
        - capturado_curl is succeeded
    msg: 'Nginx no está corriendo :('
    success_msg: 'Nginx está corriendo :)'
    
# Comprobar que la configuración aplicada es correcta
- name: Comprobar que la configuración se está aplicando
  assert:
    that:
        - "'fichero de la web' in capturado_curl.stdout"
    msg: 'Nginx no está correctamente configurado TT'
    success_msg: 'Nginx está correctamente configurado XD'